#!/bin/bash

git submodule update --recursive --init

pushd awitpt
git checkout v0.1.x
git pull
popd

pushd opentrafficshaper/plugins/webserver/pages/static/awit-flot-toolkit
git checkout
git pull
popd

